import { PetAtlasLayout, PetAtlasRowDef, PetConfig, PetCustom, PetInteraction, ResolvedPet } from './types';
export declare const CUSTOM_PET_ID = "custom";
export declare const FRAMES_MIN = 1;
export declare const FRAMES_MAX = 24;
export declare const FPS_MIN = 1;
export declare const FPS_MAX = 30;
export declare const DEFAULT_PET_CONFIG: PetConfig;
export declare function defaultCustomPet(): PetCustom;
export declare function resolveActivePet(pet: PetConfig | undefined): ResolvedPet | null;
export declare function preferredRowId(state: PetInteraction): string;
export declare function pickAtlasRow(layout: PetAtlasLayout | undefined, preferred: string): PetAtlasRowDef | undefined;
export declare function pickAmbientRow(layout: PetAtlasLayout | undefined, avoidId?: string): PetAtlasRowDef | null;
export declare function ambientLines(name: string): string[];
